import React from 'react';
import { Link } from 'react-router-dom';
import { Facebook, Twitter, Instagram, Mail, Phone, MapPin } from 'lucide-react';
export default function Footer() {
    return (React.createElement("footer", { className: "bg-gray-900 text-gray-300 mt-16" },
        React.createElement("div", { className: "container mx-auto px-4 py-12" },
            React.createElement("div", { className: "grid grid-cols-1 md:grid-cols-4 gap-8" },
                React.createElement("div", null,
                    React.createElement("div", { className: "flex items-center gap-2 mb-4" },
                        React.createElement("div", { className: "text-3xl" }, "\uD83D\uDC3E"),
                        React.createElement("span", { className: "text-white text-xl" }, "WarmPaws")),
                    React.createElement("p", { className: "text-sm" }, "Your trusted companion for pet care during winter. Keeping your furry friends warm, safe, and healthy.")),
                React.createElement("div", null,
                    React.createElement("h3", { className: "text-white mb-4" }, "Quick Links"),
                    React.createElement("ul", { className: "space-y-2 text-sm" },
                        React.createElement("li", null,
                            React.createElement(Link, { to: "/", className: "hover:text-white transition-colors" }, "Home")),
                        React.createElement("li", null,
                            React.createElement(Link, { to: "/my-profile", className: "hover:text-white transition-colors" }, "My Profile")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "#services", className: "hover:text-white transition-colors" }, "Services")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "#tips", className: "hover:text-white transition-colors" }, "Winter Tips")))),
                React.createElement("div", null,
                    React.createElement("h3", { className: "text-white mb-4" }, "Contact Us"),
                    React.createElement("ul", { className: "space-y-3 text-sm" },
                        React.createElement("li", { className: "flex items-center gap-2" },
                            React.createElement(Phone, { size: 16 }),
                            React.createElement("span", null, "+1 (555) 123-4567")),
                        React.createElement("li", { className: "flex items-center gap-2" },
                            React.createElement(Mail, { size: 16 }),
                            React.createElement("span", null, "info@warmpaws.com")),
                        React.createElement("li", { className: "flex items-center gap-2" },
                            React.createElement(MapPin, { size: 16 }),
                            React.createElement("span", null, "123 Pet Street, NY 10001")))),
                React.createElement("div", null,
                    React.createElement("h3", { className: "text-white mb-4" }, "Follow Us"),
                    React.createElement("div", { className: "flex gap-4" },
                        React.createElement("a", { href: "https://facebook.com", target: "_blank", rel: "noopener noreferrer", className: "hover:text-white transition-colors" },
                            React.createElement(Facebook, { size: 24 })),
                        React.createElement("a", { href: "https://twitter.com", target: "_blank", rel: "noopener noreferrer", className: "hover:text-white transition-colors" },
                            React.createElement(Twitter, { size: 24 })),
                        React.createElement("a", { href: "https://instagram.com", target: "_blank", rel: "noopener noreferrer", className: "hover:text-white transition-colors" },
                            React.createElement(Instagram, { size: 24 }))))),
            React.createElement("div", { className: "border-t border-gray-800 mt-8 pt-8 text-sm text-center" },
                React.createElement("div", { className: "flex flex-col md:flex-row justify-between items-center gap-4" },
                    React.createElement("p", null, "\u00A9 2025 WarmPaws. All rights reserved."),
                    React.createElement("div", { className: "flex gap-6" },
                        React.createElement(Link, { to: "/privacy", className: "hover:text-white transition-colors" }, "Privacy Policy"),
                        React.createElement(Link, { to: "/terms", className: "hover:text-white transition-colors" }, "Terms of Service")))))));
}
